/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicinterface;

import book.Book;
import book.BookDao;
import copy.Copy;
import copy.CopyDao;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Claudio Alcantara &lt;claudio.alcantara at ifnmg.edi.br&gt;
 */
public class CadastrarAtualizarExemplar extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarAtualizarExemplar
     */    
    MaskFormatter mfdata;
    private static CadastrarAtualizarExemplar instancia;
    private TelaPrincipal telaPrincipal;
    private List<Book> books;
    
    private CadastrarAtualizarExemplar(TelaPrincipal telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
        try {
            mfdata = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        initComponents();
        loadTable();
    }
    
    public static CadastrarAtualizarExemplar getInstance(TelaPrincipal telaPrincipal) {
        if (instancia == null) {
            instancia = new CadastrarAtualizarExemplar(telaPrincipal);
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtExemplarCondicao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtExemplarAquisicao = new javax.swing.JFormattedTextField(mfdata);
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnExemplarSalvar = new javax.swing.JButton();
        btnExemplarCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCadastrarAtualizarExemplar = new javax.swing.JTable();
        bntTblExemReload = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Condição:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Data de aquisição:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Selecione o Livro:");

        jButton1.setText("Adicionar Livro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnExemplarSalvar.setText("Salvar");
        btnExemplarSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExemplarSalvarActionPerformed(evt);
            }
        });

        btnExemplarCancelar.setText("Cancelar");
        btnExemplarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExemplarCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel2.setText("CADASTRO DE EXEMPLAR");

        tblCadastrarAtualizarExemplar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autores", "Edição", "Páginas", "Ano"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCadastrarAtualizarExemplar);

        bntTblExemReload.setLabel("Recarregar");
        bntTblExemReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTblExemReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtExemplarAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtExemplarCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntTblExemReload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(btnExemplarCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnExemplarSalvar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtExemplarCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtExemplarAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExemplarSalvar)
                            .addComponent(btnExemplarCancelar)))
                    .addComponent(bntTblExemReload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExemplarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExemplarCancelarActionPerformed
        dispose();
        instancia = null;
    }//GEN-LAST:event_btnExemplarCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CadastrarAtualizarLivro cadastrarAtualizarLivro = CadastrarAtualizarLivro.getInstance(telaPrincipal);
        telaPrincipal.getPrincipalPnl().add(cadastrarAtualizarLivro);
        cadastrarAtualizarLivro.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bntTblExemReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTblExemReloadActionPerformed
        loadTable();
    }//GEN-LAST:event_bntTblExemReloadActionPerformed

    private void btnExemplarSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExemplarSalvarActionPerformed
        Copy copy = new Copy();
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            copy.setAcquisition(LocalDate.parse(txtExemplarAquisicao.getText(), formatter));
            copy.setCondition(txtExemplarCondicao.getText());
            copy.setAvailable(true);
            copy.setBook(books.get(tblCadastrarAtualizarExemplar.getSelectedRow()));
        } catch (Exception ex) {
            Logger.getLogger(CadastrarAtualizarExemplar.class.getName()).log(Level.SEVERE, null, ex);
        }
        new CopyDao().saveOrUpdate(copy);
    }//GEN-LAST:event_btnExemplarSalvarActionPerformed
    
    private void loadTable(){
        books = new BookDao().findAll();
        DefaultTableModel model = (DefaultTableModel)tblCadastrarAtualizarExemplar.getModel();
        model.setNumRows(0);
        //tblCadastrarAtualizarExemplar.getColumnModel().getColumn(0).setPreferredWidth(20);
        books.forEach(book -> {
            model.addRow(new Object[]{
                book.getTitle(),
                book.getAuthors(),
                book.getEdition(),
                book.getPages(),
                book.getYear()
            });
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button bntTblExemReload;
    private javax.swing.JButton btnExemplarCancelar;
    private javax.swing.JButton btnExemplarSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCadastrarAtualizarExemplar;
    private javax.swing.JTextField txtExemplarAquisicao;
    private javax.swing.JTextField txtExemplarCondicao;
    // End of variables declaration//GEN-END:variables
}
