/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicinterface;

import copy.Copy;
import copy.CopyDao;
import credential.Credential;
import credential.CredentialDao;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import librarian.Librarian;
import loan.Loan;
import loan.LoanDao;
import reader.ReaderDao;
import user.User;

/**
 *
 * @author Claudio Alcantara &lt;claudio.alcantara at ifnmg.edi.br&gt;
 */
public class EmprestimoScreen extends javax.swing.JInternalFrame {
    
    private MaskFormatter mfdata;
    private static EmprestimoScreen instancia;
    List<Copy> copies;
    boolean fill = false;
    Librarian librarian;
    DefaultTableModel model;
    int selectedCopy;
    Credential credential;
    /**
     * Creates new form EmprestimoScreen
     */
    private EmprestimoScreen(Librarian librarian) {
        try {
            mfdata = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        initComponents();
        this.librarian = librarian;
        txtEmpresetimoScreenNacimento.setEditable(false);
        txtEmprestimoScreenDocumento.setEditable(false);
        txtEmprestimoScreenEmail.setEditable(false);
        txtEmprestimoScreenNome.setEditable(false);
        btnEmprestimoScreeenEmprestar.setEnabled(false);
        ckbEmprestimoScreeen.setEnabled(false);
        txtEmpresetimoScreenNacimento.setEnabled(false);
        txtEmprestimoScreenDocumento.setEnabled(false);
        txtEmprestimoScreenEmail.setEnabled(false);
        txtEmprestimoScreenNome.setEnabled(false);
        loadTable();
    }
    
    public static EmprestimoScreen getInstance(Librarian librarian) {
        if (instancia == null) {
            instancia = new EmprestimoScreen(librarian);
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmprestimoScreenUser = new javax.swing.JTextField();
        btnEmprestimoScreeenProcurarReader = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        txtEmprestimoScreenNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmprestimoScreenDocumento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmprestimoScreenEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmprestimoScreeen = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtEmprestimoScreenProcurarLivro = new javax.swing.JTextField();
        btnEmprestimoScreeenProcurarLivro = new javax.swing.JButton();
        btnEmprestimoScreeenEmprestar = new javax.swing.JButton();
        btnEmprestimoScreeenCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtEmprestimoScreenSenha = new javax.swing.JPasswordField();
        ckbEmprestimoScreeen = new javax.swing.JCheckBox();
        txtEmpresetimoScreenNacimento = new javax.swing.JFormattedTextField(mfdata);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setText("EMPRESTIMO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Usuário do leitor:");

        btnEmprestimoScreeenProcurarReader.setText("Procurar");
        btnEmprestimoScreeenProcurarReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoScreeenProcurarReaderActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Data de Nascimento:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Documento:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("E-mail:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Dados do Leitor");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Selecione o exemplar");

        tblEmprestimoScreeen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Autores", "Edição", "Páginas", "Ano", "Condição", "Aquisição", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmprestimoScreeen);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Digite o nome do livro:");

        txtEmprestimoScreenProcurarLivro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmprestimoScreenProcurarLivroFocusLost(evt);
            }
        });
        txtEmprestimoScreenProcurarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmprestimoScreenProcurarLivroActionPerformed(evt);
            }
        });

        btnEmprestimoScreeenProcurarLivro.setText("Procurar");
        btnEmprestimoScreeenProcurarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoScreeenProcurarLivroActionPerformed(evt);
            }
        });

        btnEmprestimoScreeenEmprestar.setText("Emprestar");
        btnEmprestimoScreeenEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoScreeenEmprestarActionPerformed(evt);
            }
        });

        btnEmprestimoScreeenCancelar.setText("Cancelar");
        btnEmprestimoScreeenCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoScreeenCancelarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Senha:");

        ckbEmprestimoScreeen.setText("Concordo com os termos e confirmo o emprestimo.");
        ckbEmprestimoScreeen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbEmprestimoScreeenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmprestimoScreenProcurarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmprestimoScreeenProcurarLivro))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ckbEmprestimoScreeen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEmprestimoScreeenCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEmprestimoScreeenEmprestar)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmprestimoScreenNome, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmpresetimoScreenNacimento))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmprestimoScreenUser, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmprestimoScreenSenha)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnEmprestimoScreeenProcurarReader))
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmprestimoScreenDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmprestimoScreenEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmprestimoScreenUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnEmprestimoScreeenProcurarReader)
                    .addComponent(jLabel10)
                    .addComponent(txtEmprestimoScreenSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmprestimoScreenNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmpresetimoScreenNacimento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmprestimoScreenDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmprestimoScreenEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtEmprestimoScreenProcurarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmprestimoScreeenProcurarLivro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmprestimoScreeenEmprestar)
                    .addComponent(btnEmprestimoScreeenCancelar)
                    .addComponent(ckbEmprestimoScreeen))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmprestimoScreeenProcurarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoScreeenProcurarLivroActionPerformed
        for(Copy copy:copies){
           if(copy.getBook().getTitle().equals(txtEmprestimoScreenProcurarLivro.getText())){
               model.setNumRows(0);
               model.addRow(new Object[]{
                copy.getBook().getTitle(),
                copy.getBook().getAuthors(),
                copy.getBook().getEdition(),
                copy.getBook().getPages(),
                copy.getBook().getYear(),
                copy.getCondition(),
                copy.getAcquisition().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))
            });
            selectedCopy = copies.indexOf(copy);
           }
           if(txtEmprestimoScreenProcurarLivro.getText().trim().isEmpty())
               loadTable();
        }
    }//GEN-LAST:event_btnEmprestimoScreeenProcurarLivroActionPerformed

    private void btnEmprestimoScreeenEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoScreeenEmprestarActionPerformed
        Loan loan = new Loan();
        loan.setReader(new ReaderDao().findById(credential.getUser().getId()));
        loan.getReader().setId(credential.getUser().getId());
        if(tblEmprestimoScreeen.getSelectedRow() != -1){
            if(loan.getReader().getQtdEmpretimos() < 3){
                loan.getReader().setQtdEmpretimos(loan.getReader().getQtdEmpretimos()+1);
                loan.setDataDoEmprestimo(LocalDate.now());
                loan.setLibrarian(librarian);
                System.out.println(librarian);
                loan.setCopy(copies.get(tblEmprestimoScreeen.getSelectedRow()));
                loan.setId(new LoanDao().saveOrUpdate(loan));
                copies.get(tblEmprestimoScreeen.getSelectedRow()).setAvailable(false);
                new CopyDao().saveOrUpdate(copies.get(tblEmprestimoScreeen.getSelectedRow()));
                new ReaderDao().saveOrUpdate(loan.getReader());
            }
            btnEmprestimoScreeenEmprestar.setEnabled(false);
            btnEmprestimoScreeenCancelar.setText("Sair");
        }
    }//GEN-LAST:event_btnEmprestimoScreeenEmprestarActionPerformed

    private void ckbEmprestimoScreeenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbEmprestimoScreeenActionPerformed
        if(ckbEmprestimoScreeen.isContentAreaFilled() == true)
            btnEmprestimoScreeenEmprestar.setEnabled(true);
        else
            btnEmprestimoScreeenEmprestar.setEnabled(false);
    }//GEN-LAST:event_ckbEmprestimoScreeenActionPerformed

    private void btnEmprestimoScreeenProcurarReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoScreeenProcurarReaderActionPerformed
        credential = new Credential();
        credential.setUser(new User());
        try {
            credential.setUsername(txtEmprestimoScreenUser.getText());
            credential.setPassword(new String(txtEmprestimoScreenSenha.getPassword()));
        } catch (Exception ex) {
            System.out.println(ex);
        }
        CredentialDao credentialDao = new CredentialDao();
        credential.setUser(credentialDao.authenticate(credential));
        if(credential.getUser() != null){
            if(new ReaderDao().findById(credential.getUser().getId()) != null){
                credential.getUser().setCredential(credential);
                txtEmprestimoScreenNome.setText(credential.getUser().getName());
                txtEmprestimoScreenEmail.setText(credential.getUser().getEmail());
                txtEmpresetimoScreenNacimento.setText(credential.getUser().getBirthDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                txtEmpresetimoScreenNacimento.setEnabled(true);
                txtEmprestimoScreenDocumento.setEnabled(true);
                txtEmprestimoScreenEmail.setEnabled(true);
                txtEmprestimoScreenNome.setEnabled(true);
                ckbEmprestimoScreeen.setEnabled(true);
                loadTable();
            }
        }
        else{
            //new ErrorScreen(this, 0).setVisible(true);
        }
    }//GEN-LAST:event_btnEmprestimoScreeenProcurarReaderActionPerformed

    private void txtEmprestimoScreenProcurarLivroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmprestimoScreenProcurarLivroFocusLost
        if(txtEmprestimoScreenProcurarLivro.getText().trim().isEmpty()){
            loadTable();} 
    }//GEN-LAST:event_txtEmprestimoScreenProcurarLivroFocusLost

    private void btnEmprestimoScreeenCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoScreeenCancelarActionPerformed
        dispose();
        instancia = null;
    }//GEN-LAST:event_btnEmprestimoScreeenCancelarActionPerformed

    private void txtEmprestimoScreenProcurarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmprestimoScreenProcurarLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmprestimoScreenProcurarLivroActionPerformed

    private void loadTable(){
        if(!fill)
            copies = new CopyDao().findAll();
        model = (DefaultTableModel) tblEmprestimoScreeen.getModel();
        model.setNumRows(0);
        for(int i =0; i<copies.size();i++){
            if(copies.get(i).isAvailable() == true){
                model.addRow(new Object[]{
                    copies.get(i).getBook().getTitle(),
                    copies.get(i).getBook().getAuthors(),
                    copies.get(i).getBook().getEdition(),
                    copies.get(i).getBook().getPages(),
                    copies.get(i).getBook().getYear(),
                    copies.get(i).getCondition(),
                    copies.get(i).getAcquisition().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))
                });
            }
        }
        fill=true;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmprestimoScreeenCancelar;
    private javax.swing.JButton btnEmprestimoScreeenEmprestar;
    private javax.swing.JButton btnEmprestimoScreeenProcurarLivro;
    private javax.swing.JToggleButton btnEmprestimoScreeenProcurarReader;
    private javax.swing.JCheckBox ckbEmprestimoScreeen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmprestimoScreeen;
    private javax.swing.JFormattedTextField txtEmpresetimoScreenNacimento;
    private javax.swing.JTextField txtEmprestimoScreenDocumento;
    private javax.swing.JTextField txtEmprestimoScreenEmail;
    private javax.swing.JTextField txtEmprestimoScreenNome;
    private javax.swing.JTextField txtEmprestimoScreenProcurarLivro;
    private javax.swing.JPasswordField txtEmprestimoScreenSenha;
    private javax.swing.JTextField txtEmprestimoScreenUser;
    // End of variables declaration//GEN-END:variables
}
